// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZmQnptNiisizybQmZe8jG0HP0n60o6dg',
    appId: '1:1031620961897:web:87bf8ea482d3c5aec164f8',
    messagingSenderId: '1031620961897',
    projectId: 'my-card-app-7878784547',
    authDomain: 'my-card-app-7878784547.firebaseapp.com',
    storageBucket: 'my-card-app-7878784547.appspot.com',
    measurementId: 'G-NN32ZCFDY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ZeHc-0LtACSynSbgO88-KvRs0GEecCE',
    appId: '1:1031620961897:android:f3b0a171c168154fc164f8',
    messagingSenderId: '1031620961897',
    projectId: 'my-card-app-7878784547',
    storageBucket: 'my-card-app-7878784547.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAAKH_EyB2hHc5C_yKsCwSeH4NawvD0rU',
    appId: '1:1031620961897:ios:63d854cac4284a4bc164f8',
    messagingSenderId: '1031620961897',
    projectId: 'my-card-app-7878784547',
    storageBucket: 'my-card-app-7878784547.appspot.com',
    iosClientId:
        '1031620961897-0rbevmo5vjtg4i2juqnid5ee7bqk6lvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAAKH_EyB2hHc5C_yKsCwSeH4NawvD0rU',
    appId: '1:1031620961897:ios:63d854cac4284a4bc164f8',
    messagingSenderId: '1031620961897',
    projectId: 'my-card-app-7878784547',
    storageBucket: 'my-card-app-7878784547.appspot.com',
    iosClientId:
        '1031620961897-0rbevmo5vjtg4i2juqnid5ee7bqk6lvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardapp',
  );
}
